{{- if not .Values.existingApiKeySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-api-key-secret" .Release.Name }}
  labels:
    {{- include "acryl-api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  acryl.api.key.secret: {{ randAlphaNum 32 | b64enc | quote }}
{{- end -}}