apiVersion: v2
name: acryl-prerequisites
description: A Helm chart for packages that Datahub depends on
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.3
dependencies:
  # This chart deploys an enterprise version of kafka that requires commercial license
  # Note, Schema registry and kafka rest proxy do not require the commercial license
  - name: cp-helm-charts
    version: 0.6.0
    repository: https://confluentinc.github.io/cp-helm-charts/
    condition: cp-helm-charts.enabled
maintainers:
  - name: DataHub
    email: datahub@acryl.io
