apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" .Release.Name "datahub-mae-consumer" }}
  labels:
    {{- include "datahub-mae-consumer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.datahub.mae_consumer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "datahub-mae-consumer.selectorLabels" . | nindent 4 }}
